language: android

jdk: oraclejdk8
sudo: false

branches:
  only:
    - master

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - platform-tools
    - build-tools-28.0.3
    - android-27
    - android-28
    - extra-android-support
    - extra-android-m2repository

script:
  ./gradlew :valifi:test
